DROP TABLE IF EXISTS Customers;
GO
DROP TABLE IF EXISTS Orders;
GO
DROP TABLE IF EXISTS OrderItems;
GO
DROP TABLE IF EXISTS Products;
GO
DROP TABLE IF EXISTS Shipments;
GO

CREATE TABLE Customers (
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	Name VARCHAR(50) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Country VARCHAR(30),
	City VARCHAR(30),
	Detail VARCHAR(100),
	ZipCode VARCHAR(6)
);
GO

CREATE TABLE Orders (
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	CustomerId INT NOT NULL,
	ShipmentId INT NOT NULL
);
GO

CREATE TABLE OrderItems (
	OrderId INT NOT NULL,
	ProductId INT NOT NULL,
	ProductPrice INT NOT NULL,
	ProductQuantity INT NOT NULL
);
GO

CREATE TABLE Products (
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	Name VARCHAR(100) NOT NULL,
	Description VARCHAR(200),
	ImageUrl VARCHAR(100),
	Price INT NOT NULL,
	Quantity INT NOT NULL
);
GO

CREATE TABLE Shipments (
	Id INT NOT NULL PRIMARY KEY IDENTITY,
	Type INT NOT NULL,
	Status INT NOT NULL,
	Country VARCHAR(30) NOT NULL,
	City VARCHAR(30) NOT NULL,
	Detail VARCHAR(100) NOT NULL,
	ZipCode VARCHAR(6) NOT NULL
);
GO
